networks:
  main:
  logs:
    external: true

services:
  backend:
    build: .
    depends_on:
      - sqlserver
    ports:
      - '127.0.0.1:3501:3001'
    environment:
      - PathBase=/api
      - ASPNETCORE_ENVIRONMENT
      - ASPNETCORE_URLS=http://+:3001
      - ConnectionStrings__DefaultConnection=Server=sqlserver;User=sa;Password=SenhaForte123!;TrustServerCertificate=True;
    volumes:
      - ./logs/backend:/app/logs
      - ./keys:/root/.aspnet/DataProtection-Keys
    networks:
      - main
      - logs
    restart: unless-stopped
    pull_policy: build

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SenhaForte123!
    ports:
      - '1433:1433'
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - main

volumes:
  sql_data:
